- name: Ping bastion
  ping:

- name: Copy SSH public key
  delegate_to: localhost
  expect:
    command: ssh-copy-id {{ '-i %s' % opentlc_ssh_identity_file if opentlc_ssh_identity_file is defined else '' }} {{ ansible_user}}@{{ opentlc_bastion_short_hostname|default(inventory_hostname_short) }}.{{ opentlc_guid }}.{{ opentlc_domain|default('example.opentlc.com') }}
    responses:
      ' connecting (yes/no)? ': 'yes'

# vim:sw=2:ts=2:et:
